name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download QEMU image file
      run: |
        echo "Downloading QEMU image file..."
        curl -L -o "qemu-img-windows-x64-${{ github.ref_name }}.zip" "https://cloudbase.it/downloads/qemu-img-win-x64-2_3_0.zip"
        echo "Download completed successfully"
        ls -la "qemu-img-windows-x64-${{ github.ref_name }}.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          qemu-img-windows-x64-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        body: |
          - Source: https://cloudbase.it/downloads/qemu-img-win-x64-2_3_0.zip
